import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:dentist_directory/models/patient.dart';
import 'package:dentist_directory/screens/view_patient_screen.dart';
import 'package:dentist_directory/utils/firestore.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AddPatientScreen extends StatefulWidget {
  final User _user;

  const AddPatientScreen({Key? key, required User user})
      : _user = user,
        super(key: key);

  @override
  State<AddPatientScreen> createState() => _AddPatientScreenState();
}

class _AddPatientScreenState extends State<AddPatientScreen> {
  DateTime dateTime = DateTime(2023, 01, 19);

  // DateTime dateTime =DateTime(2023,01,19);
  final _firstNameController = TextEditingController();
  final _lastNameController = TextEditingController();
  final _phoneNumberController = TextEditingController();
  final _pageNumberController = TextEditingController();

  // final _dateOfBirthController = TextEditingController();
  //FocusNode _dateOfBirthFocusNode = FocusNode();
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  final Future<SharedPreferences> _prefs = SharedPreferences.getInstance();
  late Future<String> userId;
  late String currentUserId = '';

  final TextEditingController _dateOfBirthController = TextEditingController();
  final FocusNode _dateOfBirthFocusNode = FocusNode();

  final _firstNameKey = GlobalKey();
  final _lastNameKey = GlobalKey();
  final _dateOfBirthNameKey = GlobalKey();
  final _phoneNumberKey = GlobalKey();
  final _pageNumberKey = GlobalKey();

  final String requireFieldValidateMsg =
      "patient_page.require_field_validate_msg".tr();
  String formTitle = "patient_page.form_title".tr();

  @override
  void dispose() {
    super.dispose();
    _firstNameController.dispose();
    _lastNameController.dispose();
    _dateOfBirthController.dispose();
    _phoneNumberController.dispose();
    _pageNumberController.dispose();
    _dateOfBirthFocusNode.dispose();
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    userId = _prefs.then((SharedPreferences prefs) {
      currentUserId = prefs.getString('uid') ?? '';
      return prefs.getString('uid') ?? '';
    });
  }

  Future savePatient() async {
    try {
      if (!_formKey.currentState!.validate()) {
        return;
      } else {
        Patient patient = Patient.empty(
            _firstNameController.text,
            _lastNameController.text,
            _dateOfBirthController.text,
            _phoneNumberController.text,
            _pageNumberController.text,
            currentUserId);
        FireStore.addEntryWithAutogeneratedId('patient', patient.toMap())
            .then((value) {
          Navigator.of(context).pushReplacement(
            MaterialPageRoute(
              builder: (context) => ViewPatientScreen(
                user: widget._user,
              ),
            ),
          );
        });
        // showSuccessAlert(context);
      }
    } catch (error) {
      // executed for errors of all types other than Exception
      print(error);
      // showErrorAlert(context, error);
    }
  }

  // Map<String, dynamic> data = snapshot.data!.data() as Map<String, dynamic>;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: SingleChildScrollView(
          child: Form(
            key: _formKey,
            child: Container(
              height: MediaQuery.of(context).size.height,
              padding: const EdgeInsets.all(15.0),
              decoration: const BoxDecoration(
                image: DecorationImage(
                  image: AssetImage("assets/images/background.jpg"),
                  fit: BoxFit.cover,
                  opacity: 0.4,
                ),
              ),
              child: Container(
                margin: const EdgeInsets.symmetric(
                    vertical: 15.0, horizontal: 15.0),
                child: Column(
                  children: <Widget>[
                    TextFormField(
                      key: _firstNameKey,
                      controller: _firstNameController,
                      validator: (String? value) {
                        if (value == null || value.isEmpty) {
                          return requireFieldValidateMsg;
                        } else {
                          return null;
                        }
                      },
                      decoration: InputDecoration(
                        labelText: "patient_page.first_name".tr(),
                        prefixIcon: const Icon(
                            Icons.person), // Add person icon for first name
                      ),
                      style: Theme.of(context).textTheme.bodyLarge,
                    ),
                    const SizedBox(
                      height: 25,
                    ),
                    TextFormField(
                      key: _lastNameKey,
                      controller: _lastNameController,
                      validator: (String? value) {
                        if (value == null || value.isEmpty) {
                          return requireFieldValidateMsg;
                        } else {
                          return null;
                        }
                      },
                      decoration: InputDecoration(
                        labelText: "patient_page.last_name".tr(),
                        prefixIcon: const Icon(
                            Icons.person), // Add person icon for last name
                      ),
                      style: Theme.of(context).textTheme.bodyLarge,
                    ),
                    const SizedBox(
                      height: 25,
                    ),
                    TextFormField(
                      key: _dateOfBirthNameKey,
                      controller: _dateOfBirthController,
                      focusNode: _dateOfBirthFocusNode,
                      validator: (String? value) {
                        // if (value == null || value.isEmpty) {
                        //   return requireFieldValidateMsg;
                        // } else {
                        //   return null;
                        // }
                        return null;
                      },
                      decoration: InputDecoration(
                        labelText: "patient_page.date_of_birth".tr(),
                        prefixIcon: const Icon(Icons.calendar_today),
                        // Add calendar icon for date of birth
                        hintText:
                            '${dateTime.day}/${dateTime.month}/${dateTime.year}',
                        // focusedBorder: OutlineInputBorder(borderSide: BorderSide(color: Colors.blue))
                      ),
                      onTap: () async {
                        DateTime? newDate = await showDatePicker(
                            context: context,
                            initialDate: dateTime != null ? dateTime : DateTime.now(),
                            firstDate: DateTime(1900),
                            lastDate: DateTime.now());
                        if (newDate == null) return;
                        setState(() {
                          dateTime = newDate;
                          _dateOfBirthController.text =
                              '${dateTime.day}/${dateTime.month}/${dateTime.year}'; // Tarih değerini kaydet
                        });
                      },
                      onEditingComplete: () {
                        _dateOfBirthFocusNode
                            .unfocus(); // Form alanından çıkıldığında (tarih seçiminden sonra), odak durumunu kaldırır.
                      },
                      style: Theme.of(context).textTheme.bodyLarge,
                    ),
                    const SizedBox(
                      height: 25,
                    ),
                    TextFormField(
                      key: _pageNumberKey,
                      controller: _pageNumberController,
                      validator: (String? value) {
                        if (value == null || value.isEmpty) {
                          return requireFieldValidateMsg;
                        } else {
                          return null;
                        }
                      },
                      decoration: InputDecoration(
                        labelText: "patient_page.page_number".tr(),
                        prefixIcon: const Icon(
                            Icons.pages), // Add pages icon for page number
                      ),
                      style: Theme.of(context).textTheme.bodyLarge,
                    ),
                    const SizedBox(
                      height: 25,
                    ),
                    TextFormField(
                      key: _phoneNumberKey,
                      controller: _phoneNumberController,
                      validator: (String? value) {
                        // if (value == null || value.isEmpty) {
                        //   return requireFieldValidateMsg;
                        // } else {
                        //   return null;
                        // }
                        return null;
                      },
                      decoration: InputDecoration(
                        labelText: "patient_page.phone_number".tr(),
                        prefixIcon:
                            const Icon(Icons.phone), // Add the phone icon here
                      ),
                      style: Theme.of(context).textTheme.bodyLarge,
                    ),
                    Expanded(child: Container()),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      mainAxisSize: MainAxisSize.max,
                      children: [
                        FloatingActionButton(
                          tooltip: 'general.save'.tr(),
                          onPressed: () async {
                            await savePatient();
                          },
                          child: const Icon(Icons.save),
                        ),
                        FloatingActionButton(
                          onPressed: () {
                            var navigator = Navigator.of(context);
                            navigator.pushReplacement(
                              MaterialPageRoute(
                                builder: (context) =>
                                    ViewPatientScreen(user: widget._user),
                              ),
                            );
                          },
                          tooltip: 'general.back'.tr(),
                          child: const Icon(Icons.arrow_back_outlined),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
            // ],
          ),
        ),
      ),
    );
  }
}
