import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:dentist_directory/models/patient.dart';

class FireStore {
  // just a simple get
  static Future<List<Patient>> getAllEntries(String collection) async {
    return (await FirebaseFirestore.instance.collection(collection).get())
        .docs
        .map((item) {
      var data = item.data();
      data['id'] = item.reference.id;
      return Patient.fromMapObject(data);
    }).toList();
  }

  // get with custom order
  static Future<List<Patient>> getAllEntriesSortedByName(
      String collection, String idUser) async {

    List<Patient> result = [];
    QuerySnapshot querySnapshot = await FirebaseFirestore.instance
        .collection(collection)
        .where('id_user_created', isEqualTo: idUser)
        .orderBy("first_name", descending: false)
        .get();
    List<Map<String, dynamic>> documents = querySnapshot.docs
        .map((doc) { var data = doc.data() as Map<String, dynamic>; data['id'] = doc.id;  return data;  })
        .toList();

    for (var doc in documents) {
        result.add(Patient.fromMapObject(doc)); // print data of each document
    }
    return result;
  }

  // get with filter
  static Future<Patient?> getEntryById(String collection, String id) async {
    DocumentSnapshot<Map<String, dynamic>>? snapshot =
        await FirebaseFirestore.instance.collection(collection).doc(id).get();

    Map<String, dynamic>? data = snapshot.data();
    if (data != null) {
      var map = <String, dynamic>{};
      map['id'] = id;
      map['first_name'] = data['first_name'];
      map['last_name'] = data['last_name'];
      map['date_of_birth'] = data['date_of_birth'];
      map['phone_number'] = data['phone_number'];
      map['page_number'] = data['page_number'];
      map['id_user_created'] = data['id_user_created'];
      return Patient.fromMapObject(map);
    } else {
      print('The document does not exist');
    }
    return null;
  }

  static Future addEntryWithAutogeneratedId(
      String collection, Map<String, dynamic> data) async {
    await FirebaseFirestore.instance.collection(collection).add(data);
  }

  // updates an existing entry (missing fields won't be touched on update), document must exist
  static Future updateEntryWithId(
      String collection, String documentId, Map<String, dynamic> data) async {
    await FirebaseFirestore.instance
        .collection(collection)
        .doc(documentId)
        .update(data);
  }

  // adds or updates an existing entry (missing fields will be deleted on update!), document will be created if needed
  static Future addOrUpdateWithId(
      String collection, String documentId, Map<String, dynamic> data) async {
    await FirebaseFirestore.instance
        .collection(collection)
        .doc(documentId)
        .set(data);
  }

  // deletes the entry with the given document id
  static Future deleteEntry(String collection, String documentId) async {
    await FirebaseFirestore.instance
        .collection(collection)
        .doc(documentId)
        .delete();
  }
}
